---
title: "comparingVehicleEmissions"
author: "Adam"
date: "2025-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load_packages, message=FALSE, warning=FALSE}
library("httr")
library("jsonlite")
```


# Example 1: Fuel Prices

```{r urls}
base_url <- "https://fueleconomy.gov/ws/rest/"
info_url <- "fuelprices"
full_url <- paste0(base_url, info_url)

full_url
```

## Call API
```{r api}
api_call <- GET(full_url)
```

## API response
```{r api_response}
# api_call["status_code"]
# api_call["content"]
api_call$status_code
api_call$content

```


## convert response to usable data
```{r data_convert}
api_char <- rawToChar(api_call$content)

api_json <- fromJSON(api_char, flatten = TRUE)
api_json

api_json$diesel
```
# Example 2

# build urls
```{r build_urls}
base_url <- "https://fueleconomy.gov/ws/rest/"
info_url <- "vehicle/menu/options?year=2012&make=Honda&model=Fit"
full_url <- paste0(base_url, info_url)

full_url
```
## check response

```{r}
api_call <- GET(full_url)
api_call$status_code
```
## convert response to usable data
```{r data_convert}
api_char <- rawToChar(api_call$content)

api_json <- fromJSON(api_char, flatten = TRUE)
# api_json

df <- api_json$menuItem
df
```


